// Auto-generated chain definitions from LiFi API
// Do not edit this file manually - run generate-chain-code.js instead

import { defineChain } from 'viem'
import { mainnet } from 'wagmi/chains'
import { optimism } from 'wagmi/chains'
import { cronos } from 'wagmi/chains'
import { bsc } from 'wagmi/chains'
import { gnosis } from 'wagmi/chains'
import { polygon } from 'wagmi/chains'
import { opBNB } from 'wagmi/chains'
import { zksync } from 'wagmi/chains'
import { moonbeam } from 'wagmi/chains'
import { mantle } from 'wagmi/chains'
import { base } from 'wagmi/chains'
import { arbitrum } from 'wagmi/chains'
import { celo } from 'wagmi/chains'
import { avalanche } from 'wagmi/chains'
import { linea } from 'wagmi/chains'
import { blast } from 'wagmi/chains'
import { scroll } from 'wagmi/chains'

// Custom chain definitions for chains not in wagmi/chains
export const allChains = {
  eth: Object.assign({}, mainnet, { lifiKey: 'eth' }),

  opt: Object.assign({}, optimism, { lifiKey: 'opt' }),

  flr: Object.assign({}, defineChain({
    id: 14,
    name: 'Flare',
    nativeCurrency: {
      name: 'Flare',
      symbol: 'FLR',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://flare-api.flare.network/ext/C/rpc'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Flare Explorer',
        url: 'https://flarescan.com/',
      },
    },
  }), { lifiKey: 'flr' }),

  cro: Object.assign({}, cronos, { lifiKey: 'cro' }),

  rsk: Object.assign({}, defineChain({
    id: 30,
    name: 'Rootstock',
    nativeCurrency: {
      name: 'Rootstock Smart Bitcoin',
      symbol: 'RBTC',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://public-node.rsk.co'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Rootstock Explorer',
        url: 'https://explorer.rootstock.io/',
      },
    },
  }), { lifiKey: 'rsk' }),

  xdc: Object.assign({}, defineChain({
    id: 50,
    name: 'XDC',
    nativeCurrency: {
      name: 'XDC',
      symbol: 'XDC',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.xdcrpc.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'XDC Explorer',
        url: 'https://xdcscan.com/',
      },
    },
  }), { lifiKey: 'xdc' }),

  bsc: Object.assign({}, bsc, { lifiKey: 'bsc' }),

  vic: Object.assign({}, defineChain({
    id: 88,
    name: 'Viction',
    nativeCurrency: {
      name: 'Viction',
      symbol: 'VIC',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.viction.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Viction Explorer',
        url: 'https://www.vicscan.xyz/',
      },
    },
  }), { lifiKey: 'vic' }),

  dai: Object.assign({}, gnosis, { lifiKey: 'dai' }),

  fus: Object.assign({}, defineChain({
    id: 122,
    name: 'FUSE',
    nativeCurrency: {
      name: 'FUSE',
      symbol: 'FUSE',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.fuse.io'],
      },
    },
    blockExplorers: {
      default: {
        name: 'FUSE Explorer',
        url: 'https://explorer.fuse.io/',
      },
    },
  }), { lifiKey: 'fus' }),

  uni: Object.assign({}, defineChain({
    id: 130,
    name: 'Unichain',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://mainnet.unichain.org'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Unichain Explorer',
        url: 'https://unichain.blockscout.com/',
      },
    },
  }), { lifiKey: 'uni' }),

  pol: Object.assign({}, polygon, { lifiKey: 'pol' }),

  mon: Object.assign({}, defineChain({
    id: 143,
    name: 'Monad',
    nativeCurrency: {
      name: 'MON',
      symbol: 'MON',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.monad.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Monad Explorer',
        url: 'https://monadscan.com/',
      },
    },
  }), { lifiKey: 'mon' }),

  son: Object.assign({}, defineChain({
    id: 146,
    name: 'Sonic',
    nativeCurrency: {
      name: 'Sonic',
      symbol: 'S',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.soniclabs.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Sonic Explorer',
        url: 'https://explorer.soniclabs.com/',
      },
    },
  }), { lifiKey: 'son' }),

  opb: Object.assign({}, opBNB, { lifiKey: 'opb' }),

  lns: Object.assign({}, defineChain({
    id: 232,
    name: 'Lens',
    nativeCurrency: {
      name: 'GHO',
      symbol: 'GHO',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://api.lens.matterhosted.dev'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Lens Explorer',
        url: 'https://explorer.lens.xyz/',
      },
    },
  }), { lifiKey: 'lns' }),

  fra: Object.assign({}, defineChain({
    id: 252,
    name: 'Fraxtal',
    nativeCurrency: {
      name: 'FRAX',
      symbol: 'FRAX',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.frax.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Fraxtal Explorer',
        url: 'https://fraxscan.com/',
      },
    },
  }), { lifiKey: 'fra' }),

  bob: Object.assign({}, defineChain({
    id: 288,
    name: 'Boba',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://mainnet.boba.network'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Boba Explorer',
        url: 'https://bobascan.com/',
      },
    },
  }), { lifiKey: 'bob' }),

  era: Object.assign({}, zksync, { lifiKey: 'era' }),

  wcc: Object.assign({}, defineChain({
    id: 480,
    name: 'World Chain',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://worldchain-mainnet.g.alchemy.com/public'],
      },
    },
    blockExplorers: {
      default: {
        name: 'World Chain Explorer',
        url: 'https://worldscan.org/',
      },
    },
  }), { lifiKey: 'wcc' }),

  flw: Object.assign({}, defineChain({
    id: 747,
    name: 'Flow',
    nativeCurrency: {
      name: 'FLOW',
      symbol: 'FLOW',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://mainnet.evm.nodes.onflow.org'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Flow Explorer',
        url: 'https://evm.flowscan.io/',
      },
    },
  }), { lifiKey: 'flw' }),

  sta: Object.assign({}, defineChain({
    id: 988,
    name: 'Stable',
    nativeCurrency: {
      name: 'gasUSDT',
      symbol: 'GUSDT',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.stable.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Stable Explorer',
        url: 'https://stablescan.xyz/',
      },
    },
  }), { lifiKey: 'sta' }),

  hyp: Object.assign({}, defineChain({
    id: 999,
    name: 'HyperEVM',
    nativeCurrency: {
      name: 'HYPE',
      symbol: 'HYPE',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.hyperliquid.xyz/evm'],
      },
    },
    blockExplorers: {
      default: {
        name: 'HyperEVM Explorer',
        url: 'https://hyperevmscan.io/',
      },
    },
  }), { lifiKey: 'hyp' }),

  mam: Object.assign({}, defineChain({
    id: 1088,
    name: 'Metis',
    nativeCurrency: {
      name: 'METIS',
      symbol: 'METIS',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://metis-public.nodies.app'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Metis Explorer',
        url: 'https://andromeda-explorer.metis.io/',
      },
    },
  }), { lifiKey: 'mam' }),

  lsk: Object.assign({}, defineChain({
    id: 1135,
    name: 'Lisk',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.api.lisk.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Lisk Explorer',
        url: 'https://blockscout.lisk.com/',
      },
    },
  }), { lifiKey: 'lsk' }),

  moo: Object.assign({}, moonbeam, { lifiKey: 'moo' }),

  sei: Object.assign({}, defineChain({
    id: 1329,
    name: 'Sei',
    nativeCurrency: {
      name: 'SEI',
      symbol: 'SEI',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://evm-rpc.sei-apis.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Sei Explorer',
        url: 'https://seitrace.com/',
      },
    },
  }), { lifiKey: 'sei' }),

  hpl: Object.assign({}, defineChain({
    id: 1337,
    name: 'Hyperliquid',
    nativeCurrency: {
      name: 'USDC',
      symbol: 'USDC',
      decimals: 6,
    },
    rpcUrls: {
      default: {
        http: ['https://li.quest/v1/rpc/1337'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Hyperliquid Explorer',
        url: 'https://app.hyperliquid.xyz/explorer/',
      },
    },
  }), { lifiKey: 'hpl' }),

  van: Object.assign({}, defineChain({
    id: 1480,
    name: 'Vana',
    nativeCurrency: {
      name: 'VAN',
      symbol: 'VAN',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.vana.org'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Vana Explorer',
        url: 'https://vanascan.io/',
      },
    },
  }), { lifiKey: 'van' }),

  gra: Object.assign({}, defineChain({
    id: 1625,
    name: 'Gravity',
    nativeCurrency: {
      name: 'G',
      symbol: 'G',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.gravity.xyz/'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Gravity Explorer',
        url: 'https://explorer.gravity.xyz/',
      },
    },
  }), { lifiKey: 'gra' }),

  soe: Object.assign({}, defineChain({
    id: 1868,
    name: 'Soneium',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.soneium.org/'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Soneium Explorer',
        url: 'https://soneium.blockscout.com/',
      },
    },
  }), { lifiKey: 'soe' }),

  swl: Object.assign({}, defineChain({
    id: 1923,
    name: 'Swellchain',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://swell-mainnet.alt.technology'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Swellchain Explorer',
        url: 'https://swellchainscan.io/',
      },
    },
  }), { lifiKey: 'swl' }),

  ron: Object.assign({}, defineChain({
    id: 2020,
    name: 'Ronin',
    nativeCurrency: {
      name: 'RON',
      symbol: 'RON',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://api.roninchain.com/rpc'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Ronin Explorer',
        url: 'https://app.roninchain.com/',
      },
    },
  }), { lifiKey: 'ron' }),

  abs: Object.assign({}, defineChain({
    id: 2741,
    name: 'Abstract',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://api.mainnet.abs.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Abstract Explorer',
        url: 'https://abscan.org/',
      },
    },
  }), { lifiKey: 'abs' }),

  mnt: Object.assign({}, mantle, { lifiKey: 'mnt' }),

  kai: Object.assign({}, defineChain({
    id: 8217,
    name: 'Kaia',
    nativeCurrency: {
      name: 'KAIA',
      symbol: 'KAIA',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://public-en.node.kaia.io'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Kaia Explorer',
        url: 'https://kaiascan.io/',
      },
    },
  }), { lifiKey: 'kai' }),

  bas: Object.assign({}, base, { lifiKey: 'bas' }),

  pla: Object.assign({}, defineChain({
    id: 9745,
    name: 'Plasma',
    nativeCurrency: {
      name: 'XPL',
      symbol: 'XPL',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.plasma.to'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Plasma Explorer',
        url: 'https://plasmascan.to/',
      },
    },
  }), { lifiKey: 'pla' }),

  imx: Object.assign({}, defineChain({
    id: 13371,
    name: 'Immutable zkEVM',
    nativeCurrency: {
      name: 'ImmutableX',
      symbol: 'IMX',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.immutable.com/'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Immutable zkEVM Explorer',
        url: 'https://explorer.immutable.com/',
      },
    },
  }), { lifiKey: 'imx' }),

  ape: Object.assign({}, defineChain({
    id: 33139,
    name: 'Apechain',
    nativeCurrency: {
      name: 'ApeCoin',
      symbol: 'APE',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.apechain.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Apechain Explorer',
        url: 'https://apescan.io/',
      },
    },
  }), { lifiKey: 'ape' }),

  mod: Object.assign({}, defineChain({
    id: 34443,
    name: 'Mode',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://mainnet.mode.network'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Mode Explorer',
        url: 'https://explorer.mode.network/',
      },
    },
  }), { lifiKey: 'mod' }),

  arb: Object.assign({}, arbitrum, { lifiKey: 'arb' }),

  cel: Object.assign({}, celo, { lifiKey: 'cel' }),

  etl: Object.assign({}, defineChain({
    id: 42793,
    name: 'Etherlink',
    nativeCurrency: {
      name: 'Tezos',
      symbol: 'XTZ',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://node.mainnet.etherlink.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Etherlink Explorer',
        url: 'https://explorer.etherlink.com/',
      },
    },
  }), { lifiKey: 'etl' }),

  hmi: Object.assign({}, defineChain({
    id: 43111,
    name: 'Hemi',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.hemi.network/rpc'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Hemi Explorer',
        url: 'https://explorer.hemi.xyz/',
      },
    },
  }), { lifiKey: 'hmi' }),

  ava: Object.assign({}, avalanche, { lifiKey: 'ava' }),

  sop: Object.assign({}, defineChain({
    id: 50104,
    name: 'Sophon',
    nativeCurrency: {
      name: 'SOPH',
      symbol: 'SOPH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.sophon.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Sophon Explorer',
        url: 'https://sophscan.xyz/',
      },
    },
  }), { lifiKey: 'sop' }),

  sup: Object.assign({}, defineChain({
    id: 55244,
    name: 'Superposition',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.superposition.so'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Superposition Explorer',
        url: 'https://explorer.superposition.so/',
      },
    },
  }), { lifiKey: 'sup' }),

  ink: Object.assign({}, defineChain({
    id: 57073,
    name: 'Ink',
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc-gel.inkonchain.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Ink Explorer',
        url: 'https://explorer.inkonchain.com/',
      },
    },
  }), { lifiKey: 'ink' }),

  lna: Object.assign({}, linea, { lifiKey: 'lna' }),

  boc: Object.assign({}, defineChain({
    id: 60808,
    name: 'BOB',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.gobob.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'BOB Explorer',
        url: 'https://explorer.gobob.xyz/',
      },
    },
  }), { lifiKey: 'boc' }),

  ber: Object.assign({}, defineChain({
    id: 80094,
    name: 'Berachain',
    nativeCurrency: {
      name: 'Bera',
      symbol: 'BERA',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.berachain.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Berachain Explorer',
        url: 'https://berascan.com/',
      },
    },
  }), { lifiKey: 'ber' }),

  bls: Object.assign({}, blast, { lifiKey: 'bls' }),

  plu: Object.assign({}, defineChain({
    id: 98866,
    name: 'Plume',
    nativeCurrency: {
      name: 'PLUME',
      symbol: 'PLUME',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.plume.org'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Plume Explorer',
        url: 'https://explorer.plume.org/',
      },
    },
  }), { lifiKey: 'plu' }),

  tai: Object.assign({}, defineChain({
    id: 167000,
    name: 'Taiko',
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.mainnet.taiko.xyz'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Taiko Explorer',
        url: 'https://taikoscan.io/',
      },
    },
  }), { lifiKey: 'tai' }),

  scl: Object.assign({}, scroll, { lifiKey: 'scl' }),

  kat: Object.assign({}, defineChain({
    id: 747474,
    name: 'Katana',
    nativeCurrency: {
      name: 'ETH',
      symbol: 'ETH',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://rpc.katana.network'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Katana Explorer',
        url: 'https://katanascan.com/',
      },
    },
  }), { lifiKey: 'kat' }),

  crn: Object.assign({}, defineChain({
    id: 21000000,
    name: 'Corn',
    nativeCurrency: {
      name: 'Bitcorn',
      symbol: 'BTCN',
      decimals: 18,
    },
    rpcUrls: {
      default: {
        http: ['https://mainnet.corn-rpc.com'],
      },
    },
    blockExplorers: {
      default: {
        name: 'Corn Explorer',
        url: 'https://cornscan.io/',
      },
    },
  }), { lifiKey: 'crn' }),
}

// Chain ID to key mapping
export const CHAIN_ID_TO_KEY: Record<number, string> = {
  1: 'eth',
  10: 'opt',
  14: 'flr',
  25: 'cro',
  30: 'rsk',
  50: 'xdc',
  56: 'bsc',
  88: 'vic',
  100: 'dai',
  122: 'fus',
  130: 'uni',
  137: 'pol',
  143: 'mon',
  146: 'son',
  204: 'opb',
  232: 'lns',
  252: 'fra',
  288: 'bob',
  324: 'era',
  480: 'wcc',
  747: 'flw',
  988: 'sta',
  999: 'hyp',
  1088: 'mam',
  1135: 'lsk',
  1284: 'moo',
  1329: 'sei',
  1337: 'hpl',
  1480: 'van',
  1625: 'gra',
  1868: 'soe',
  1923: 'swl',
  2020: 'ron',
  2741: 'abs',
  5000: 'mnt',
  8217: 'kai',
  8453: 'bas',
  9745: 'pla',
  13371: 'imx',
  33139: 'ape',
  34443: 'mod',
  42161: 'arb',
  42220: 'cel',
  42793: 'etl',
  43111: 'hmi',
  43114: 'ava',
  50104: 'sop',
  55244: 'sup',
  57073: 'ink',
  59144: 'lna',
  60808: 'boc',
  80094: 'ber',
  81457: 'bls',
  98866: 'plu',
  167000: 'tai',
  534352: 'scl',
  747474: 'kat',
  21000000: 'crn',
}

// Key to chain ID mapping
export const KEY_TO_CHAIN_ID: Record<string, number> = {
  'eth': 1,
  'opt': 10,
  'flr': 14,
  'cro': 25,
  'rsk': 30,
  'xdc': 50,
  'bsc': 56,
  'vic': 88,
  'dai': 100,
  'fus': 122,
  'uni': 130,
  'pol': 137,
  'mon': 143,
  'son': 146,
  'opb': 204,
  'lns': 232,
  'fra': 252,
  'bob': 288,
  'era': 324,
  'wcc': 480,
  'flw': 747,
  'sta': 988,
  'hyp': 999,
  'mam': 1088,
  'lsk': 1135,
  'moo': 1284,
  'sei': 1329,
  'hpl': 1337,
  'van': 1480,
  'gra': 1625,
  'soe': 1868,
  'swl': 1923,
  'ron': 2020,
  'abs': 2741,
  'mnt': 5000,
  'kai': 8217,
  'bas': 8453,
  'pla': 9745,
  'imx': 13371,
  'ape': 33139,
  'mod': 34443,
  'arb': 42161,
  'cel': 42220,
  'etl': 42793,
  'hmi': 43111,
  'ava': 43114,
  'sop': 50104,
  'sup': 55244,
  'ink': 57073,
  'lna': 59144,
  'boc': 60808,
  'ber': 80094,
  'bls': 81457,
  'plu': 98866,
  'tai': 167000,
  'scl': 534352,
  'kat': 747474,
  'crn': 21000000,
}

// Array of all chains for Wagmi
export const chainsArray = Object.values(allChains)
